name: test
on: [ push, pull_request ]
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2019 ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install D compiler
      uses: dlang-community/setup-dlang@1ccbc70a0eff7f264857b53c562aa45fd7f1e479
      with:
        compiler: dmd-2.100.0
    - name: Build
      run: dmd dhcptest.d
    - name: Upload binary
      if: ${{ matrix.os == 'windows-2019' }}
      uses: actions/upload-artifact@v2
      with:
        name: dhcptest-${{ matrix.os }}
        path: dhcptest.exe
